apiVersion: v1
kind: Service
metadata:
  name: grafana-console
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: grafana
  ports:
  - port: 3000
    targetPort: 3000
