apiVersion: placement.kubernetes-fleet.io/v1
kind: ClusterResourcePlacement
metadata:
  name: crp-foo
  labels:
    app: foo-app
spec:
  resourceSelectors:
    - group: ""
      kind: Namespace
      version: v1
      name: foo
  policy:
    placementType: PickFixed
    clusterNames: ["k8s5a"]
