apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: k8s3-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.122.230-192.168.122.239
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: k8s3
  namespace: metallb-system
spec:
  ipAddressPools:
  - k8s3-pool
